::

diff --git a/.github/workflows/infra_plan.yaml b/.github/workflows/infra_plan.yaml
--- a/.github/workflows/infra_plan.yaml
+++ b/.github/workflows/infra_plan.yaml
@@ -132,7 +132,7 @@ jobs:
           printf "$OUTPUT" > plan_output_multiline.txt
 
           # if [ "$OUTPUT" == *"error"* ]; then
-          if grep -q "Terraform exited with code" plan_output.txt || grep -q "Error: Terraform exited with code" >&2; then
+          if grep -q "::error::Terraform exited with code" plan_output.txt || grep -q "::error::Terraform exited with code" >&2; then
             # printf "result=fail" >> $GITHUB_OUTPUT
             echo "failed"
             exit 1
@@ -190,7 +190,4 @@ jobs:
         if: always() && steps.plan.outcome != 'success'
         run: |
           echo "${{steps.plan.outcome}}"
-          # if [ "${{ steps.plan.outputs.result }}" -ne "success" ]; then
-          #   echo "::error::Terraform plan failed"
           exit 1
-          # fi
