change logic

diff --git a/.github/workflows/infra_plan.yaml b/.github/workflows/infra_plan.yaml
--- a/.github/workflows/infra_plan.yaml
+++ b/.github/workflows/infra_plan.yaml
@@ -120,18 +120,18 @@ jobs:
 
           # printf "result=fail" >> $GITHUB_OUTPUT
 
-          terraform plan -lock-timeout=3000s -no-color | tee plan_output.txt
+          terraform plan -lock-timeout=3000s -no-color > plan_output.txt 2>&1
           RESULT=$?
+          echo "result is: $RESULT"
 
-          # cat plan_output.txt
+          cat plan_output.txt
 
           OUTPUT=$(grep -Ev "Refreshing state|state lock|Reading|Read" plan_output.txt | tail -c 60000)
           printf "$OUTPUT" > plan_output_multiline.txt
 
-          echo "result is: $RESULT"
-
           if [ $RESULT -ne 0 ]; then
             printf "result=fail" >> $GITHUB_OUTPUT
+            exit $RESULT
           else
             printf "result=success" >> $GITHUB_OUTPUT
           fi
@@ -140,6 +140,7 @@ jobs:
       # The plan output is posted in a comment in the PR
       - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
         name: Post Plan on PR
+        id: comment
         if: always() && github.event_name == 'pull_request'
         with:
           script: |
@@ -182,9 +183,9 @@ jobs:
 
       # Fail the workflow if the Terraform plan failed
       - name: Check Terraform Plan Result
-        if: always()
+        if: steps.plan.outcome != 'success' || steps.comment.outcome != 'success'
         run: |
-          if [ "${{ steps.plan.outputs.result }}" -ne "success" ]; then
-            echo "::error::Terraform plan failed"
+          # if [ "${{ steps.plan.outputs.result }}" -ne "success" ]; then
+          #   echo "::error::Terraform plan failed"
             exit 1
-          fi
+          # fi
