solution

diff --git a/.github/workflows/infra_plan.yaml b/.github/workflows/infra_plan.yaml
--- a/.github/workflows/infra_plan.yaml
+++ b/.github/workflows/infra_plan.yaml
@@ -118,19 +118,21 @@ jobs:
         run: |
           set -euo pipefail
 
+          printf "result=fail" >> $GITHUB_OUTPUT
+
           terraform plan -lock-timeout=3000s -no-color > plan_output.txt 2>&1
-          PLAN_EXIT_STATUS=$?
+          # PLAN_EXIT_STATUS=$?
 
           cat plan_output.txt
 
           OUTPUT=$(grep -Ev "Refreshing state|state lock|Reading|Read" plan_output.txt | tail -c 60000)
           printf "$OUTPUT" > plan_output_multiline.txt
 
-          if [ $PLAN_EXIT_STATUS -ne 0 ]; then
-            printf "result=fail" >> $GITHUB_OUTPUT
-          else
+          # if [ $PLAN_EXIT_STATUS -ne 0 ]; then
+          #   printf "result=fail" >> $GITHUB_OUTPUT
+          # else
             printf "result=success" >> $GITHUB_OUTPUT
-          fi
+          # fi
 
       # Post the plan output in the PR
       # The plan output is posted in a comment in the PR
@@ -180,7 +182,7 @@ jobs:
       - name: Check Terraform Plan Result
         if: always()
         run: |
-          if [ "${{ steps.plan.outputs.result }}" == "fail" ]; then
+          if [ "${{ steps.plan.outputs.result }}" -ne "success" ]; then
             echo "::error::Terraform plan failed"
             exit 1
           fi
